server:
  port: 8080

spring:
  jpa:
    open-in-view: false
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/template1"
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always